[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@pythnetwork/entropy-sdk-solidity/=lib/pyth-crosschain/target_chains/ethereum/entropy_sdk/solidity/"
]

# Solidity compiler settings
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = false

# Extra output
extra_output = ["storageLayout", "metadata"]
extra_output_files = ["metadata"]

# Testing
fuzz = { runs = 256 }
invariant = { runs = 256 }

# Gas reports
gas_reports = ["*"]

# Formatting
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"

# RPC endpoints
[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC}"
base = "${BASE_MAINNET_RPC}"

# Etherscan configuration for verification
[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }

# CI profile
[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

# File system permissions (add this)
fs_permissions = [
    { access = "read-write", path = "./frontend/.env.local" },
    { access = "read-write", path = "./frontend" },
    { access = "read", path = "./" }
]
